MyLibrary/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

from django.conf.urls import include
from django.urls import path

urlpatterns += [
    path('catalog/',include('catalog.urls')),
]

from django.views.generic import RedirectView

urlpatterns += [
    path('',RedirectView.as_view(url='/catalog')),
]

from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

catalog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('books/', views.BookListView.as_view(), name='books'),
    path('book/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),
    path('authors/', views.AuthorListView.as_view(), name='authors'),
    path('authors/<int:pk>', views.AuthorDetailView.as_view(), name='author-detail'),
]

catalog/models.py
from django.db import models
from django.http.response import Http404
import uuid   # https://officeguide.cc/python-generate-uuid-tutorial-examples/

# Create your models here.

class Genre(models.Model):
    name = models.CharField(max_length=200, help_text='請輸入書本類別(例如：科學書刊。)')
    
    def __str__(self):
        return self.name

from django.urls import reverse #Used to gengerate URLs by reversing the URL patterns

class Book(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    summary = models.TextField(max_length=1000, help_text='請輸入書本摘要')
    isbn = models.CharField('ISBN', max_length=13, help_text='請輸入13碼<a href="https://www.isbn-international.org/content/what-isbn">ISBN號碼</a>')
    genre = models.ManyToManyField(Genre, help_text='請選擇本書類型')
    language = models.ForeignKey('Language', on_delete=models.SET_NULL, null=True)
    
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("book-detail", args=[str(self.id)])
    
class BookInstance(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='請輸入一個UUID(獨特ID)來代表書：')
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    
    LOAN_STATUS = (
        ('m', '維護中'),
        ('o', '借出中'),
        ('a', '可借用'),
        ('r', '已預約'),
    )
    
    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='m',
        help_text='Book availability',
    )
    
    class Meta:
        ordering = ['due_back']
        
    def __str__(self):
        return f'{self.id} {{self.book.title}}'
    
class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)
    
    class Meta:
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        return reverse("author-detail", args=[str(self.id)])
    
    def __str__(self):
        return f'{self.last_name}, {self.first_name}'

class Language(models.Model):
    name = models.CharField(max_length=200, help_text='請輸入語言(例如英語、法語、德語...')
    
    def __str__(self):
        return self.name
    

catalog/views.py
from django.shortcuts import render

# Create your views here.
from .models import Book, Author, BookInstance, Genre, Http404

def index(request):
    """View function for home page of site."""
    
    # Generate counts of some of the main objects
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()
    
    # Available books (status = 'a')
    num_instances_available = BookInstance.objects.filter(status__exact='a').count()
    
    # The 'all()' is implied by default.
    num_authors = Author.objects.count()
    
    context = {
        'num_books': num_books,
        'num_instances': num_instances,
        'num_instances_available': num_instances_available,
        'num_authors': num_authors,
    }
    
    # Render the HTML template index.html with the data in the context variable
    return render(request, 'index.html', context=context)

from django.views import generic

class BookListView(generic.ListView):
    model = Book
    
class BookDetailView(generic.DetailView):
    model = Book
    
    def book_detail_view(request, primary_key):
        try:
            book = Book.objects.get(pk=primary_key)
        except Book.DoesNotExist:
            raise Http404('Book does not exist')
        return render(request, 'catalog/book_detail.html', context={'book': book})    

class AuthorListView(generic.ListView):
    model = Author
    
class AuthorDetailView(generic.DetailView):
    model = Author
    
    def author_detail_view(request, primary_key):
        try:
            author = Author.objects.get(pk=primary_key)
        except Author.DoesNotExist:
            raise Http404('Author does not exist')
        return render(request, 'catalog/author_detail.html', context={'author': author})

catalog/templates/base_generic.html
<!DOCTYPE html>
<html lang='en'>
<head>
    {% block title %}<title>Local Library</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">

    <!--Add additional CSS in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-2">
            {% block sidebar %}
            <ul class="sidebar-nav">
                <li><a href="{% url 'index' %}">Home</a></li>
                <li><a href="{% url 'books' %}">All books</a></li>
                <li><a href="{% url 'authors' %}">All authors</a></li>
            </ul>
            {% endblock %}
            </div>
            <div class="col-sm-10 ">
            {% block content %}{% endblock %}
            </div>
        </div>
    </div>
</body>
</html>

catalog/templates/catalog/author_detail.html
{% extends "base_generic.html" %}

{% block content %}
    <hl>Title:{{ author.last_name }}, {{ author.first_name }}</hl>

    <p><strong>First Name:</strong>{{ author.first_name }}</p>
    <p><strong>Last Name:</strong>{{ author.last_name }}</p>
    <p><strong>Date of Birth:</strong>{{ author.date_of_birth }}</p>
    <p><strong>Date of Death:</strong>{{ author.date_of_death }}</p>
{% endblock %}

catalog/templates/catalog/author_list.html
{% extends "base_generic.html" %}

{% block content %}
    <hl>Author List</hl>
    {% if author_list %}
        <ul>
            {% for author in author_list %}
            <li>
                <a href="{{ author.get_absolute_url }}">{{ author.last_name }}, {{ author.first_name }}</a>
            </li>
            {%　endfor %}
        </ul>
    {% else %}
        <p>There are no any authors.</p>
    {% endif %}
{% endblock %} 

catalog/templates/catalog/book_detail.html
{% extends "base_generic.html" %}

{% block content %}
    <hl>Title: {{ book.title }}</hl>

    <p><strong>Author:</strong> <a href="">{{ book.author }}</a></p> <!-- author detail link not yet defined-->
    <p><strong>Summary:</strong> {{ book.summary }}</p>
    <p><strong>ISBN:</strong>{{ book.isbn }}</p>
    <p><strong>Language:</strong>{{ book.language }}</p>
    <p><strong>Genre:</strong>{% for genre in book.genre.all %} {{ genre }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>

    <div style="margin-left:20px;margin-top:20px">
        <h4>Copies</h4>

        {% for copy in book.bookinstance_set.all %}
        <hr>
        <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">{{ copy.get_status_display }}</p>
        {% if copy.status != 'a' %}<p><strong>Due to be returned:</strong> {{copy.due_back}}</p>{% endif %}
        <p><strong>Imprint:</strong> {{copy.imprint}}</p>
        <p class="text-muted"><strong>Id:</strong> {{copy.id}}</p>
        {% endfor %}
    </div>
{% endblock %}

catalog/templates/catalog/book_list.html
{% extends "base_generic.html" %}

{% block content %}
    <hl>Book List</hl>
    {% if book_list %}
    <ul>
        {% for book in book_list %}
            <li>
                <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> {{book.author}}
            </li>
        {% endfor %}
    </ul>
    {% else %}
        <p>There are no books in the library.</p>
    {% endif %}
{% endblock %}    

catalog/templates/index.html
{%　extends "base_generic.html" %}

{% block content %}
    <hl>Local Library Home</hl>
    <p>Welcome to MyLibrary!</p>

    <h2>Dynamic content</h2>
    <p>The library has the following record counts:</p>
    <ul>
        <li><string>Books:</strong>{{ num_books}}</li>
        <li><string>Copies:</strong>{{ num_instances}}</li>
        <li><string>Copies available:</strong>{{ num_instances_available}}</li>
        <li><string>Authors:</strong>{{ num_authors}}</li>
    </ul>
{% endblock %}